name: portfolio_5410356
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_form_builder: 9.3.0
  firebase_core: ^3.2.0
firebase_core: latest_version
firebase_auth: latest_version
cloud_firestore: latest_version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
  

flutter:
  uses-material-design: true

  assets:
  - web/assets/IMG9256.jpg
  


    
