name: portfolio_5410356
description: An app built using Flutter for web

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  portfolio_5410356:
    path: src/flutter/dev/portfolio_5410356/portfolio_5410356 # Path to the local package

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
